quadrupedal_test:
  #publish joint states

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #position controllers
  left_front_leg_shoulder_rotate_controller:
    type: my_controller/MyPositionController
    joint: left_front_leg_shoulder_rotate
    gain: 500

  right_front_leg_shoulder_rotate_controller:
    type: my_controller/MyPositionController
    joint: right_front_leg_shoulder_rotate
    gain: 500

  left_back_leg_shoulder_rotate_controller:
    type: my_controller/MyPositionController
    joint: left_back_leg_shoulder_rotate
    gain: 500

  right_back_leg_shoulder_rotate_controller:
    type: my_controller/MyPositionController
    joint: right_back_leg_shoulder_rotate
    gain: 500

  left_front_leg_shoulder_hinge_controller:
    type: my_controller/MyPositionController
    joint: left_front_leg_shoulder_hinge
    gain: 500

  right_front_leg_shoulder_hinge_controller:
    type: my_controller/MyPositionController
    joint: right_front_leg_shoulder_hinge
    gain: 500

  left_back_leg_shoulder_hinge_controller:
    type: my_controller/MyPositionController
    joint: left_back_leg_shoulder_hinge
    gain: 500

  right_back_leg_shoulder_hinge_controller:
    type: my_controller/MyPositionController
    joint: right_back_leg_shoulder_hinge
    gain: 500

  left_front_leg_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: left_front_leg_elbow_hinge
    gain: 500

  right_front_leg_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: right_front_leg_elbow_hinge
    gain: 500

  left_back_leg_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: left_back_leg_elbow_hinge
    gain: 500

  right_back_leg_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: right_back_leg_elbow_hinge
    gain: 500

  left_front_calf_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: left_front_calf_elbow_hinge
    gain: 500

  right_front_calf_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: right_front_calf_elbow_hinge
    gain: 500

  left_back_calf_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: left_back_calf_elbow_hinge
    gain: 500

  right_back_calf_elbow_hinge_controller:
    type: my_controller/MyPositionController
    joint: right_back_calf_elbow_hinge
    gain: 500

  

