quadrupedal_test:
  #publish joint states

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  #position controllers
  left_front_leg_shoulder_rotate_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_leg_shoulder_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_front_leg_shoulder_rotate_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_leg_shoulder_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_leg_shoulder_rotate_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_leg_shoulder_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_leg_shoulder_rotate_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_leg_shoulder_rotate
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_front_leg_shoulder_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_leg_shoulder_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_front_leg_shoulder_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_leg_shoulder_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_leg_shoulder_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_leg_shoulder_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_leg_shoulder_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_leg_shoulder_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_front_leg_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_leg_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_front_leg_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_leg_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_leg_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_leg_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_leg_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_leg_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_front_calf_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: left_front_calf_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_front_calf_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: right_front_calf_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_back_calf_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: left_back_calf_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_back_calf_elbow_hinge_controller:
    type: effort_controllers/JointPositionController
    joint: right_back_calf_elbow_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}

  

