simpleArm:
  #publish joint states

  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 1000

  #position controllers
  left_front_leg_shoulder_rotate_controller:
    type: "effort_controllers/JointPositionController"
    joint: left_front_leg_shoulder_rotate
    pid: {p: 0.0, i: 0.0, d: 0.0}

  left_front_leg_shoulder_hinge_controller:
    type: "effort_controllers/JointPositionController"
    joint: left_front_leg_shoulder_hinge
    pid: {p: 0.0, i: 0.0, d: 0.0}

  left_front_leg_elbow_hinge_controller:
    type: "effort_controllers/JointPositionController"
    joint: left_front_leg_elbow_hinge
    pid: {p: 0.0, i: 0.0, d: 0.0}

  

